name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Print masked secret
        run: echo "The secret is:$SAMPLE_KEY"
        env:
          SAMPLE_KEY: ${{ secrets.SAMPLE_KEY }}

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...
